import './Schema.spec.js'
import './Star.spec.js'
import './Cube.spec.js'
import './Cube.query.spec.js'
import './Cube.fill.spec.js'
import './Cube.add.spec.js'
import './Cube.remove.spec.js'
import './readme.spec.js'